Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/8/2023
Var
// Seção de Declarações das variáveis
 msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   msg <- "Olá, Mundo!";
   escreva(msg)
Fimalgoritmo
